### ISSUE TITLE
No icon in calendar after submitting Bonus request

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1143]
Icon in calendar on Dashboard is missing after submitting bonus leave request  .

**Comment by jprotic** [comment]
FE doesn't receive valid data for getUserDays call. It receives data for all absence types, except for bonus days.

**Comment by slobodanc93** [comment]
After detailed code and business analysis, conclusion is that bonus days should not be displayed in the calendar. When a bonus day is approved, it will increase the total allowance and can later be spent when needed according to standard rules.
I think that we can close this issue if you agree.

**Comment by jglugonja** [comment]
Agreement is made. This issue will be closed.
