### ISSUE TITLE
Change Error message when editing Leave type name to existing one

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1146]
Steps to reproduce: 
1. Log in with HR credentials
2. Click on Administration many
3. Click on Leave Types tab
4. Click on existing Leave type 
5. Change name of Leave type to already existing
6. Click on button Save

Actual result:

![Screenshot_2020-01-09 Hawaii execom](https://user-images.githubusercontent.com/58041536/72062220-a3760680-32d7-11ea-9b0c-9062a45b9530.png)

Sugestion:
Leave Type with same name already exist.

**Comment by nefeyel** [comment]
This happens also when creating new leave type (Absence) with existing name, not only with editing

**Comment by jglugonja** [comment]
This issue is still reproducible. On the other hand, correct error message is shown when creating new leave type (Absence) with existing name (Absence type: Bonus Days already exists).

**Comment by jglugonja** [comment]
This issue is fixed.
