### ISSUE TITLE
Ignored exceptions

### ISSUE THREAD

**Issue by stefankaticec** [execom-eu/hawaii#1148]
There are ignored exceptions in the code. This usually leads to bugs that are hard to find later on. As a rule of thumb, never ignore an exception. Either handle it and recover from it or propagate it.

Some examples:
EmailService.sendEmail
EmailService.createEmail
EmailService.getTemplate
GoogleCalendarService::init
SendNotificationService:send

You can either wrap these exceptions into your own (prefered) or use [SneakyThrows](https://projectlombok.org/features/SneakyThrows).

There are two instances where RuntimeException was thrown. This makes it very hard to do proper exception handling, as all unchecked exceptions derive from RuntimeException. Both these cases are related to doing reflection, so replacing it with IllegalStateException should do the job.

**Comment by nefeyel** [comment]
It's not possible for method to return a boolean value after throwing exception.. How can it be solved. Not leaving it without returning value (false in this case) or changing to return void?

**Comment by stefankaticec** [comment]
I'm sorry, i don't understand what you are asking - how can what be solved?
Throwing an exception breaks the stack and propagates out of methods until it reaches the end. The end for an exception is either a catch statement or program exit.
