### ISSUE TITLE
Users without Start professional career date don't have Carried over days

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1189]
Imported users without Start professional career date will not have Carried over days. For this users Carried over days will be updated automatically by hrassistant@execom.eu on January 1st (visible in Audit tab) but this change will not be visible. Actual result shows allowance without Carried over days. 

![no_carried_over-days](https://user-images.githubusercontent.com/58041536/72984656-8ae01300-3de4-11ea-96e7-7b1b099a8a58.gif)

**Comment by slobodanc93** [comment]
Currently on hold. Needs to be re-tested after the closing of #1213.

**Comment by slobodanc93** [comment]
File **allowance-import.csv** if present will override existing values in the database.
So basically the JOB scheduled for 1st January was successful and updated carried over days, but data in the import file later changed carried over days to initial values.
**The solution** is to implement a validation when importing allowances to check if data is already in the database (based on a combination of user and year).
