### ISSUE TITLE
Add Approver's leaves to team calendar 

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1215]
End users (employees) suggested new enhancement. 
User should be able to see Team leader`s leaves in Team calendar.

**Comment by jglugonja** [comment]
Team leader's leaves are not visible in List view.
![NotClickable](https://user-images.githubusercontent.com/58041536/76319168-1a7f4980-62df-11ea-9f8f-29deb0b725cf.gif)

**Comment by popovicbojan** [comment]
This commit also fixes #1242
