### ISSUE TITLE
List view button does not appear clickable

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1241]
Steps to reproduce:
1. Go to Team Calendar page
2. Try to click on List view button
3. Try to click on Calendar view button

Actual result: 
1. List view button does not appear clickable. 
2. Calendar view button does not appear clickable.

![NotClickable](https://user-images.githubusercontent.com/58041536/76317894-2d911a00-62dd-11ea-8c81-5f856c1c8fd3.gif)

**Comment by MiljkovicVeljko** [comment]
Fixed with z-index.
