### ISSUE TITLE
Security Alert - X-Content-Type-Options Header Missing

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1257]
The Anti-MIME-Sniffing header X-Content-Type-Options was not set to 'nosniff'. This allows older versions of Internet Explorer and Chrome to perform MIME-sniffing on the response body, potentially causing the response body to be interpreted and displayed as a content type other than the declared content type. Current (early 2014) and legacy versions of Firefox will use the declared content type (if one is set), rather than performing MIME-sniffing.

URL:

1. https://hawaii2.execom.eu/service-worker.js

2. https://hawaii2.execom.eu/

3. https://hawaii2.execom.eu/?token=

4. https://hawaii2.execom.eu/static/js/main.c1104239.js

5. https://hawaii2.execom.eu/index.html?_sw-precache=9d2bcbe94988931035a113f86c1f5f4e

6. https://hawaii2.execom.eu/static/css/main.a0b1ecc0.css

**Comment by popovicbojan** [comment]
MIME sniffing vulnerabilities can occur when a website allows users to upload data to the server. I don't think it is relevant to us because users can't upload anything to server.
