### ISSUE TITLE
Security Alert - Cross Site Scripting Weakness (Reflected in JSON Response)

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1259]
A XSS attack was reflected in a JSON response, this might leave content consumers vulnerable to attack if they don't appropriately handle the data (response).

URL:

1. https://hawaii2.execom.eu/api/users

2. https://hawaii2.execom.eu/api/leavetypes?size=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E&page=0

3. https://hawaii2.execom.eu/api/teams?page=0&size=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

4. https://hawaii2.execom.eu/api/publicholidays?deleted=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

5. https://hawaii2.execom.eu/api/users/search?page=0&size=30&userStatusType=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

6. https://hawaii2.execom.eu/api/requests/user/year?year=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

7. https://hawaii2.execom.eu/api/users/teamCalendarList?month=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E&teamId=

8. https://hawaii2.execom.eu/api/leavetypes?size=30&page=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

9. https://hawaii2.execom.eu/api/allowances/user/year?year=2020&userId=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

10. https://hawaii2.execom.eu/api/requests/team/month?yearMonth=2020-03&teamId=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

11. https://hawaii2.execom.eu/api/users/days?year=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

12. https://hawaii2.execom.eu/api/publicholidays/year?year=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

13. https://hawaii2.execom.eu/api/requests/team/month?yearMonth=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E&teamId=

14. https://hawaii2.execom.eu/api/teams?page=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E&size=30

15. https://hawaii2.execom.eu/api/allowances/user/year?year=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E&userId=16

16. https://hawaii2.execom.eu/api/users/teamCalendarList?month=2020-03&teamId=%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

**Comment by popovicbojan** [comment]
This is handled at backend. Sending HTTP request to any of the URLs above will raise MethodArgumentTypeMismatchException and response code will be `400 - Bad Request`.

**Comment by popovicbojan** [comment]
Review this: @stanislavgrujic

**Comment by stanislavgrujic** [comment]
I was not able to run these scripts (neither from browser nor from Postman), so I don't think there is anything else we need to do here.
