### ISSUE TITLE
Change audit information after deletion cancellation 

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1281]
Audit information after deletion cancellation does not contain correct data.

![Screenshot_2020-03-26 Hawaii execom(1)](https://user-images.githubusercontent.com/58041536/77654026-c2984200-6f70-11ea-9e80-db97a32fae5f.png)

**Comment by stanislavgrujic** [comment]
What do you expect to be correct data here?

**Comment by jglugonja** [comment]
Something like:
STOPPED WORKING AT EXECOM
                  27.03.2020.
                          ↓
                CANCELLED

**Comment by slobodanc93** [comment]
@jglugonja Maybe we could just use '-' as an absence of data? It would be a frontend change.
STOPPED WORKING AT EXECOM
27.03.2020.
↓
-

**Comment by jglugonja** [comment]
@slobodanc93 I agree with you.
