### ISSUE TITLE
Manual adjustment tab recalculates filed on unsuccessful submit

### ISSUE THREAD

**Issue by popovicbojan** [execom-eu/hawaii#1296]
When submitting form, values are changed and request is send to backend, after request doesn't pass validation at backend error is displayed and frontend multiplies other fields by 8 (recalculates days in hours). Frontend validation needs to be in accordance with validation at backend. 

![captured](https://user-images.githubusercontent.com/50595862/78868362-190e8180-7a43-11ea-9282-cb312e3a07b3.gif)

**Comment by VojislavKovacevic** [comment]
fix confirmed for field manual adjust
The same issue appears on fields Bonus days and Carried over

**Comment by VojislavKovacevic** [comment]
A similar issue occurs when a manual adjust field is populated after error. 

steps: 
1. enter number higher than allowed in field manual adjust 
2. submit 
3. request rejected
4. enter a valid number in manual adjust field 
5. values in carried over and bonus days are multiplied with 8

![Hawaii-execom-Google-Chrome-2020-04-30-13-55-23](https://user-images.githubusercontent.com/63228397/80708932-c4fc3780-8aec-11ea-90be-905145b96650.gif)
