### ISSUE TITLE
Administration tab missing on mobile version

### ISSUE THREAD

**Issue by VojislavKovacevic** [execom-eu/hawaii#1327]
Administration tab missing on the mobile version. 

![tab missing2020-04-30 12_05_39-Hawaii execom](https://user-images.githubusercontent.com/63228397/80698836-4cd94600-8adb-11ea-9bd3-057cdb983905.png)

![tab present2020-04-30 12_07_27-Settings](https://user-images.githubusercontent.com/63228397/80698839-4fd43680-8adb-11ea-82af-122621b205dd.png)

**Comment by popovicbojan** [comment]
This is actually specified by the client. :)
Hr managers shouldn't administrate application on mobile devices.
