### ISSUE TITLE
Field names in Edit tab are clickable

### ISSUE THREAD

**Issue by jglugonja** [execom-eu/hawaii#1332]
Field names in Edit tab are clickable and cursor change is present. If User clicks on the field name the result will be the same as when he clicks on the input field.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/58041536/80947144-d2b50400-8def-11ea-9976-26fe8cd03710.gif)

This issue appears in all Edit tabs (Years, Teams, Employees, etc).

**Comment by popovicbojan** [comment]
This is actually a desired functionality. It enables better precision on smaller screens, e.g. mobile phones. I think it would look better without pointer cursor, so I'll disable on hover cursor change.
