### ISSUE TITLE
Fetch user data after login

### ISSUE THREAD

**Issue by vrackovic** [execom-eu/hawaii#134]
Backend:
- [x] Endpoint `/me` should be created. Closest thing we have atm is `/user/{email}`. 
- It will be used to fetch data about logged user.
- [ ] Model should be changed so that `userImage` could be stored and loaded from db (blob)
Suggestion: Return info from decoded `idToken`

Frontend: 
- [x] Remove current implementation where random users are fetched from `https://randomuser.me/api/`
- [x] Implement User store, saga, service, and display users information in `TopHeader` and `InformationHeader`
- [x] Style `TopHeader` and `InformationHeader` as suggested by design.

**Comment by JonathanTolic** [comment]
Added /me endpoint; userImage pending
