### ISSUE TITLE
Admin dashboard tab not aligned properly on mobile 

### ISSUE THREAD

**Issue by VojislavKovacevic** [execom-eu/hawaii#1404]
Admin dashboard tab not aligned properly on a mobile device.

Do we really need a tab with metrics on mobile devices?

![Admin board2020-06-09 10_16_20-Hawaii execom](https://user-images.githubusercontent.com/63228397/84123766-9605a980-aa3a-11ea-94cf-f9a970260502.png)

![AdDash2020-06-09 10_21_46-Hawaii execom](https://user-images.githubusercontent.com/63228397/84124148-1c21f000-aa3b-11ea-8461-9c94a95630bf.png)

**Comment by popovicbojan** [comment]
I'll turn off Admin Dashboard on mobile devices.
