### ISSUE TITLE
Add field maxBonusForRelevantWorkExperience to Leave Profile edit and create pages

### ISSUE THREAD

**Issue by mariobasic** [execom-eu/hawaii#680]

**Comment by mariobasic** [comment]
Hovering on this filed should bring pop up message explaining what it does.

Scheduler checks every day to see if employee has 5 or more  years of relevant work experience. If employee has 5 years of relevant work experience he will be awarded 1 bonus day, if he has 6 years of relevant work experience 2 bonus days will be added to his allowance. Number of days that user can receive for amount of work experience is set in this field. If `maxBonusForRelevantWorkExperience `is set to 40 hours user can be awarded a maximum of 5 bonus days no matter of the amount of work experience that he/she has.

If `maxBonusForRelevantWorkExperience` is set to 0, employees that have that leave profile will not receive bonus days.

**Comment by ffpetrovic** [comment]
Should `0` be the default value sent to the backend, if nothing is entered in the field? Or is `maxBonusForRelevantWorkExperience` a mandatory field?

**Comment by mariobasic** [comment]
`maxBonusForRelevantWorkExperience` will be mandatory field.

**Comment by ffpetrovic** [comment]
Ask for explanation text
