### ISSUE TITLE
Mobile sidebar scroll

### ISSUE THREAD

**Issue by aberonja** [execom-eu/hawaii#789]
Check with the rest of the team should mobile menu sidebar be more compact. 

e.g. Should image be smaller so that scroll can be removed

**Comment by ffpetrovic** [comment]
![image](https://user-images.githubusercontent.com/5026566/63760998-ab04b800-c8c0-11e9-8223-542364aeb03e.png)

**Comment by aberonja** [comment]
Fine with me. Don't merge it until you check with headmasters 🇭🇷 👑 🌴
