### ISSUE TITLE
Edit public holiday error

### ISSUE THREAD

**Issue by aberonja** [execom-eu/hawaii#832]
Please, change date formatting to dd MMM yyyy (05 Sep 2019).

![image](https://user-images.githubusercontent.com/35724583/64331264-c3688700-cfd2-11e9-8a9f-48b6dc649246.png)

**Comment by mariobasic** [comment]
![image](https://user-images.githubusercontent.com/45662818/64333296-8f8f6080-cfd6-11e9-85a0-347376486760.png)

**Comment by mariobasic** [comment]
This format is the one requested?

**Comment by aberonja** [comment]
Can you make it without any dashes? 
07 May 2019
