### ISSUE TITLE
Remove submit cancellation button if request status is cancellation pending

### ISSUE THREAD

**Issue by aberonja** [execom-eu/hawaii#886]
![image](https://user-images.githubusercontent.com/35724583/64866334-84be7680-d63b-11e9-8d5a-9498db2bb9a6.png)

**Comment by stanislavgrujic** [comment]
This is also a backend issue - it should not allow addition of another cancelation request, if one already exists.

**Comment by jglugonja** [comment]
This issue is non reproducible.
