### ISSUE TITLE
Team additional mails are not send to backend

### ISSUE THREAD

**Issue by mariobasic** [execom-eu/hawaii#887]
![image](https://user-images.githubusercontent.com/45662818/64868274-462abb00-d63f-11e9-916f-29da5e040ee1.png)

**Comment by ffpetrovic** [comment]
![image](https://user-images.githubusercontent.com/5026566/64940102-65a22d80-d863-11e9-8a43-791268abe49d.png)

'Preview' is the preview of the server's response.
