### ISSUE TITLE
Leave request link present in emails outside of Execom domain

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#911]
Steps to reproduce:

- Create/edit team with emails outside of the Execom domain in the "Annual request emails" field
- Submit a request as one of the members of the above used team

Expected result: The email outside of the domain only gets notified of the leave request
Actual result: The email outside of the domain also gets a link to the request, which they cannot use anyway.
![firefox_92tc698RSp](https://user-images.githubusercontent.com/54444325/65235063-2e878280-dad6-11e9-8e00-8cd4ee7889d7.png)

**Comment by mariobasic** [comment]
Question: 
Is this wanted behavior? Is it expected that emails outside of _execom_ domain have also email with _execom_ domain which they can use to access the site? Should we add another template which does not have link leading to our app? Or should we restrict additional emails to _execom_ domain only?

**Comment by stanislavgrujic** [comment]
No. At the moment, we want to support only execom domain emails/accounts.
