### ISSUE TITLE
Dashboard does not look the same on different PC browsers

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#912]
Firefox:

![firefox_YD2K8ABPMM](https://user-images.githubusercontent.com/54444325/65235783-98ecf280-dad7-11e9-8e01-2f6d10f75040.png)

Google Chrome:

![chrome_0MCZ3wJXWu](https://user-images.githubusercontent.com/54444325/65235849-b15d0d00-dad7-11e9-9f6d-909a99c10e2c.png)

**Comment by stanislavgrujic** [comment]
It would be useful to mark what is different. It is not obvious.

**Comment by rgerstmajer-ec** [comment]
EDIT:
The differences are:
- Borders not clear on weekend and non-existent days' cells on Firefox
- Year field has different borders
