### ISSUE TITLE
Team calendar does not look the same on different PC browsers

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#913]
Firefox:

![firefox_IQLw82fb8F](https://user-images.githubusercontent.com/54444325/65236028-00a33d80-dad8-11e9-9dac-6463b9b27f86.png)

Google Chrome:

![chrome_PP0orx0aWc](https://user-images.githubusercontent.com/54444325/65236068-14e73a80-dad8-11e9-93ba-a122460a3769.png)

**Comment by rgerstmajer-ec** [comment]
EDIT:
The noted differences are:
- Borders of days are not visible on Firefox
- Day number fields are not aligned on Firefox as they are on Google Chrome
- Year and Team Name fields have different borders on each browser

**Comment by jglugonja** [comment]
This issue is solved.
