### ISSUE TITLE
Page content lost after URL redirection

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#919]
Steps to reproduce:

- Log in to Hawaii
- In the address bar change "dashboard" to "login" and press the "Enter" key
- Press back

Expected result: Should stay on login page, or retain login session ( logout was not clicked )
Actual result: Lost login session, retaining sidebar items, but losing content.
![url_redirect](https://user-images.githubusercontent.com/54444325/65239891-4106b980-dae0-11e9-92b7-f298b2b7fcfc.gif)

**Comment by jglugonja** [comment]
This issue is non reproducible.
