### ISSUE TITLE
Team audit is barely human readable

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#920]
Team Audit tab displays hectic information. What was supposed to be seen in this tab?

![Team_audit_readability_1](https://user-images.githubusercontent.com/54444325/65241498-f129f180-dae3-11e9-9343-c802f624e930.png)
![Team_audit_readability_2](https://user-images.githubusercontent.com/54444325/65241499-f1c28800-dae3-11e9-9352-925109547db9.png)

**Comment by danilo996** [comment]
We are going to open a discussion related to this issue at our next weekly meeting.
