### ISSUE TITLE
Cannot add Manual adjust leave allowance

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#921]
Steps to reproduce:

- Log in as HR Manager
- Go to Administration page
- Go to Employees tab
- Edit a random employee
- Go to Manual adjust sub-tab
- Change 1 or more of the following to random numbers: Bonus days; Carried over; Manual adjust ( Leave and Training & education )
- Enter a comment
- Click "Save"

Expected result: Changes get saved or an error message stating why the action is not able to be completed.
Actual result: Some fields get red borders with no explanation.

![Manual_adjust](https://user-images.githubusercontent.com/54444325/65243671-0ce3c680-dae9-11e9-9550-480123a34058.gif)

**Comment by danilo996** [comment]
@rgerstmajer-ec This is not an issue. The smallest amount of days which can be requested in our application is half-day(4 hours). So, you can't update allowance with a value that is not divisible by four. This situation is handled on the backend with an error response, which contains suitable information about why the allowance can't be updated. However, as we can see, there is no message which should help the final user realize what is going on and why he can't update allowance. Frontend doesn't allow final user to send the request, so they should handle this situation with a proper message.
