### ISSUE TITLE
When session times out, "unauthorized" error pops up

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#923]
Steps to reproduce:

- Log in to Hawaii
- Do anything for an hour

Expected result: After 1 hour ( or however long the sessions become ) the user is prompted to log in again with "Session expired" message
Actual result: "Unauthorized" error message pops up.

**Comment by jglugonja** [comment]
Session now times out after 7 days. This is not an issue any more.
