### ISSUE TITLE
Leave type icons not shown

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#925]
Steps to reproduce:

- Log in to Hawaii as HR manager
- Go to Administration page
- Select "Leave types" tab
- Select any existing Leave type to edit or click on the red + ( plus ) button to try to create a new one

Expected result: Select icon has visible icons shown
Actual result: The relative paths of the icons are shown:
![firefox_uefgr6OdLa](https://user-images.githubusercontent.com/54444325/65245994-f4c27600-daed-11e9-8f9a-f00a22d1fff4.png)

**Comment by jglugonja** [comment]
This issue is non reproducible.
