### ISSUE TITLE
New Administration employee can see Approvals page when not an approver

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#943]
Steps to reproduce:

- Log in as HR Manager
- Create new employee with "Administration" User Role
- Assign to a team
- Leave "Approver in teams" empty
- Log in as new employee

Expected result: Approvals page is not visible
Actual result: Approvals page is visible in the sidebar

**Comment by rgerstmajer-ec** [comment]
![Admin_employee_bugs](https://user-images.githubusercontent.com/54444325/65512860-62014d00-deda-11e9-94e5-27c407fa07f6.gif)

**Comment by jglugonja** [comment]
This bug become non reproducible.
