### ISSUE TITLE
Cursor doesn't change on clickable element

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#947]
Steps to reproduce:

- Log in as HR manager
- Go to Administration page
- Go to Teams tab
- Select a team which has an approver
- Scroll down to approvers and hover over the "x" on the right-hand side

Expected result: Cursor changes to indicate clickable element and correct cursor positioning
Actual result: Cursor does not change

![Team_edit_X_button](https://user-images.githubusercontent.com/54444325/65513993-b4dc0400-dedc-11e9-997e-a029aedd2b07.png)

**Comment by jglugonja** [comment]
This issue is resolved.
