### ISSUE TITLE
Trying to quickly get from employee edit screen to dashboard causes white screen

### ISSUE THREAD

**Issue by rgerstmajer-ec** [execom-eu/hawaii#972]
Steps to reproduce:

- Log in as HR Manager
- Go to Administration page
- Select Employees tab
- Select random employee
- Wait for Edit sidebar to load
- Rapidly click on dashboard to get to it as fast as possible

Expected result: Sidebar closes and dashboard is loaded
Actual result: Sidebar closes and white screen appears. Back button does nothing, only refreshing the page shows result.

![Clicking_dashboard_from_employee_edit](https://user-images.githubusercontent.com/54444325/65878617-cc106b00-e38e-11e9-8b92-bf1d127d59c0.gif)

**Comment by jglugonja** [comment]
This issue is resolved with new design.
